# Generated by Django 4.0.3 on 2022-04-04 11:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='Username', max_length=30)),
                ('email', models.EmailField(default='abc@abc.abc', max_length=100, unique=True)),
                ('phone', models.CharField(default='1234567890', max_length=10, unique=True)),
                ('text', models.TextField(default='feedback hear', max_length=1000)),
            ],
        ),
    ]
